# Generated by Django 3.2.3 on 2021-06-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('nik', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('departemen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('judul', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(max_length=255)),
                ('lokasi', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('url_progress', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
